export const ADDONS_LIST = [
    { key: 'toRent', label: 'À louer' },
    { key: 'rented', label: 'Loué' },
    { key: 'toSell', label: 'À vendre' },
    { key: 'sold', label: 'Vendu' },
    { key: 'plex', label: 'Plex' },
    { key: 'duplex', label: 'Duplex' },
    { key: 'triplex', label: 'Triplex' },
    { key: 'quadriplex', label: 'Quadriplex' },
    { key: 'groundFloor', label: 'Rez-de-chaussée' },
    { key: 'secondFloor', label: '2e étage' },
    { key: 'thirdFloor', label: '3e étage' },
    { key: 'condo', label: 'Condo' },
    { key: 'waterfront', label: 'Bord de l\'eau' },
    { key: 'land', label: 'Terrain' },
    { key: 'pool', label: 'Piscine' },
    { key: 'customAddon', label: 'Ajout personnalisé' },
    { key: 'openHouse', label: 'Visite libre' },
    { key: 'other', label: 'Autres' },
];